### ISSUE TITLE
Add/Remove Inputs/Ennemies

### ISSUE THREAD

**Issue by cmorent** [svknoe/WH40k-Point-Efficiency-Calculator#12]
Hi there, thanks for your awesome work!

I'm trying to add/remove units from the inputs/enemies, is there any simple way to do it? So far, when I try to do so, it results with a lot of REF errors. I saw there were a lot of hidden sheets and I was wondering if I'd have to update all of them manually or if there's another way?

Thanks!

**Comment by svknoe** [comment]
Hi

You can add and remove units in the Input and Enemies tab. Simply remove the text that is already there, and add your own. You do not have to edit any other tabs.

One possible explanation for the REF errors is the use of cut-paste. Doing so changes references. To avoid this issue I use copy-paste instead, and manually delete the additional text.

If this does not fix the problem, could you supply me with an example where this goes wrong?
