### ISSUE TITLE
Tau flamer 

### ISSUE THREAD

**Issue by frozenowni** [svknoe/WH40k-Point-Efficiency-Calculator#16]
Hi,
Is there a way to input the tau flamers d6+2 shots?
Cant seem to find it.
Thanks and Br
Jonas

**Comment by svknoe** [comment]
@frozenowni Hi Jonas

Currently this is not handled automatically. I'll add it to the todo list. Thanks!

In the meantime you can solve it by calculating the average of d6+2 to be 3.5+2=5.5. If you give the flamer 5.5 attacks then you will get the correct average damage.

Best regards

**Comment by svknoe** [comment]
This was fixed a year ago in version 6.1a, but I forgot to say so here.
