### ISSUE TITLE
reference error

### ISSUE THREAD

**Issue by AJSwogger** [svknoe/WH40k-Point-Efficiency-Calculator#20]
Data input past row 47 generates reference errors in the rest of the sheet

![image](https://github.com/svknoe/WH40k-Point-Efficiency-Calculator/assets/13993904/c9462649-cedb-4004-b77c-6abc1f931b33)

**Comment by svknoe** [comment]
Thanks a lot! The problem was in tab `wnds - regular`. I didn't copy the formula there far enough when making version 7.1a.

v7.1b fix: 547584c
